apiVersion: apps/v1
kind: Deployment
metadata:
  name: navigation-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navigation-app
  template:
    metadata:
      labels:
        app: navigation-app
    spec:
      hostAliases:
        - ip: "134.96.216.207"
          hostnames:
            - "dsl-cluster-master"
      containers:
        - name: navigation-app
          image: julialtmeyer/robo-navigation-ms
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: navigation-app-config
            - secretRef:
                name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: navigation-app-service
  labels:
    app: navigation-app
spec:
  type: NodePort
  selector:
    app: navigation-app
  ports:
    - port: 8080
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: navigation-app-config
data:
  spring.datasource.url: jdbc:mysql://${MYSQL_SERVICE_HOST}:3306/robot_maps
  nodeToleranzX: "10"
  nodeToleranzY: "10"
  mapId: "1"
  gridSpacing: "10"
  server.port: "8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  spring.datasource.username: cm9vdA==
  spring.datasource.password: YWRtaW4=